#!/usr/bin/env node
/**
 * Install the Sound Garden demo into an RPG Maker MZ or MV project.
 *
 *   node demo/install.js <path-to-project> [--dev]
 *
 *   --dev   also enable FugsAudio8Test (the in-game test() console runner)
 *
 * Use a NEW project (File > New Project in the editor), not one you care about. The installer:
 *   - copies the plugin pack into js/plugins/ and enables it in js/plugins.js
 *   - copies the demo's audio and images into audio/ and img/
 *   - adds a "Fugs Sound Garden" tileset and a "Sound Garden" map
 *   - makes the new map the starting map and names switches 11-14
 * Files it changes are backed up first to <project>/fugs-demo-backup/<time>/.
 * Running it again updates the demo in place (same tileset and map ids).
 */
"use strict";

const fs = require("fs");
const path = require("path");
const { buildGarden, gardenTileset, SWITCH_NAMES, START } = require("./tools/garden");

const repo = path.resolve(__dirname, "..");
const assets = path.join(__dirname, "game");
const PACK = [
  "FugsMultiTrackAudioEX",
  "FugsAudio0Docs",
  "FugsAudio2Effects",
  "FugsAudio3Spatial",
  "FugsAudio4Dynamics",
  "FugsAudio5Switch",
  "FugsAudio6Aliases",
  "FugsAudio7Compat",
];
const TEST_PLUGIN = "FugsAudio8Test";
const MAP_NAME = "Sound Garden";

function fail(msg) {
  console.error("install: " + msg);
  process.exit(1);
}
function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8").replace(/^﻿/, ""));
}
function writeJson(file, value) {
  fs.writeFileSync(file, JSON.stringify(value));
}
function copyTree(src, dst, skip) {
  let n = 0;
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name), d = path.join(dst, entry.name);
    if (entry.isDirectory()) {
      n += copyTree(s, d, skip);
    } else if (!skip || !skip(entry.name)) {
      fs.mkdirSync(dst, { recursive: true });
      fs.copyFileSync(s, d);
      n++;
    }
  }
  return n;
}

/** @plugindesc and @param defaults from a plugin header, so Plugin Manager shows real values. */
function pluginHeader(src) {
  const block = (src.match(/\/\*:[\s\S]*?\*\//) || [""])[0];
  const description = ((block.match(/@plugindesc\s+([^\n]*)/) || [])[1] || "").trim();
  const parameters = {};
  // only top-level @param entries (stop at the first @command: its @args are not parameters)
  const head = block.split(/\n\s*\*\s*@command\b/)[0];
  for (const part of head.split(/\n\s*\*\s*@param\s+/).slice(1)) {
    const name = part.split("\n")[0].trim();
    const def = part.match(/@default\s+([^\n]*)/);
    parameters[name] = def ? def[1].trim() : "";
  }
  return { description, parameters };
}

function readPlugins(file) {
  const src = fs.readFileSync(file, "utf8");
  return new Function(src + "\nreturn $plugins;")();
}
function writePlugins(file, list) {
  const lines = list.map((p) => JSON.stringify(p));
  fs.writeFileSync(
    file,
    "// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n" + lines.join(",\n") + "\n];\n"
  );
}

function main() {
  const args = process.argv.slice(2);
  const dev = args.includes("--dev");
  const target = args.find((a) => !a.startsWith("--"));
  if (!target) fail("usage: node demo/install.js <path-to-project> [--dev]");
  const project = path.resolve(target);
  const js = path.join(project, "js"), data = path.join(project, "data");

  const engine = fs.existsSync(path.join(js, "rmmz_core.js")) ? "mz" : fs.existsSync(path.join(js, "rpg_core.js")) ? "mv" : null;
  if (!engine) fail(project + " is not an RPG Maker MZ or MV project (no js/rmmz_core.js or js/rpg_core.js)");
  for (const f of ["System.json", "MapInfos.json", "Tilesets.json", "Troops.json"]) {
    if (!fs.existsSync(path.join(data, f))) fail("missing data/" + f);
  }
  const troops = readJson(path.join(data, "Troops.json"));
  if (!troops[1]) fail("the demo's battle uses troop 1, but data/Troops.json has none");

  // ---- back up everything we are about to rewrite
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backup = path.join(project, "fugs-demo-backup", stamp);
  fs.mkdirSync(backup, { recursive: true });
  for (const rel of ["data/System.json", "data/MapInfos.json", "data/Tilesets.json", "js/plugins.js"]) {
    const f = path.join(project, rel);
    if (fs.existsSync(f)) fs.copyFileSync(f, path.join(backup, path.basename(rel)));
  }

  // ---- plugins
  const wanted = PACK.concat(dev ? [TEST_PLUGIN] : []);
  fs.mkdirSync(path.join(js, "plugins"), { recursive: true });
  for (const name of wanted) fs.copyFileSync(path.join(repo, name + ".js"), path.join(js, "plugins", name + ".js"));
  const pluginsFile = path.join(js, "plugins.js");
  const existing = fs.existsSync(pluginsFile) ? readPlugins(pluginsFile) : [];
  const ours = new Set(PACK.concat([TEST_PLUGIN, "FugsAudio1Core"]));
  const kept = existing.filter((p) => p && !ours.has(p.name));
  const previous = new Map(existing.filter((p) => p && ours.has(p.name)).map((p) => [p.name, p]));
  const added = wanted.map((name) => {
    const h = pluginHeader(fs.readFileSync(path.join(repo, name + ".js"), "utf8"));
    const old = previous.get(name);
    return { name, status: true, description: h.description, parameters: Object.assign(h.parameters, old ? old.parameters : {}) };
  });
  writePlugins(pluginsFile, kept.concat(added));

  // ---- audio + images (MZ only plays .ogg; MV also uses .m4a in browsers without Ogg)
  const files = copyTree(assets, project, (name) => engine === "mz" && name.endsWith(".m4a"));

  // ---- tileset
  const tilesetsFile = path.join(data, "Tilesets.json");
  const tilesets = readJson(tilesetsFile);
  const tileset = gardenTileset();
  const oldTs = tilesets.find((t) => t && t.name === tileset.name);
  tileset.id = oldTs ? oldTs.id : tilesets.length;
  tilesets[tileset.id] = tileset;
  writeJson(tilesetsFile, tilesets);

  // ---- map
  const infosFile = path.join(data, "MapInfos.json");
  const infos = readJson(infosFile);
  const oldInfo = infos.find((m) => m && m.name === MAP_NAME);
  const mapId = oldInfo ? oldInfo.id : infos.length;
  const order = infos.reduce((m, i) => (i ? Math.max(m, i.order) : m), 0) + 1;
  infos[mapId] = oldInfo || { id: mapId, expanded: false, name: MAP_NAME, order, parentId: 0, scrollX: 0, scrollY: 0 };
  writeJson(infosFile, infos);
  const map = buildGarden(engine);
  map.tilesetId = tileset.id;
  const mapFile = path.join(data, "Map" + String(mapId).padStart(3, "0") + ".json");
  writeJson(mapFile, map);

  // ---- start position + switch names
  const systemFile = path.join(data, "System.json");
  const system = readJson(systemFile);
  system.startMapId = mapId;
  system.startX = START.x;
  system.startY = START.y;
  const warnings = [];
  for (const [id, name] of Object.entries(SWITCH_NAMES)) {
    const cur = system.switches[id];
    if (cur && cur !== name) warnings.push(`switch ${id} was named "${cur}"; the demo uses it as "${name}"`);
    system.switches[id] = name;
  }
  writeJson(systemFile, system);

  console.log(`Installed the Sound Garden into ${project} (RPG Maker ${engine.toUpperCase()})`);
  console.log(`  plugins:  ${wanted.join(", ")}`);
  console.log(`  assets:   ${files} files in audio/ and img/`);
  console.log(`  map:      ${path.relative(project, mapFile)} "${MAP_NAME}" (start map), tileset ${tileset.id}`);
  console.log(`  backup:   ${path.relative(project, backup)}`);
  for (const w of warnings) console.log("  warning:  " + w);
  console.log("Reopen the project in the editor (or press Playtest) to play the demo.");
}

main();
